config/routes.rb
#   Copyright (c) 2010-2011, Diaspora Inc.  This file is
#   licensed under the Affero General Public License version 3 or later.  See
#   the COPYRIGHT file.

require 'sidekiq/web'
require 'sidetiq/web'

Diaspora::Application.routes.draw do

  get 'application/staticpage'
 
  get '/tags/tosalamander'

  get 'external_data/pulldata'

  get 'external_data/pushdata'

  get 'external_data/displaydata'

  get 'external_data/homepage'

  get 'external_data/stream'

  get 'external_data/home'


  resources :report, :except => [:edit, :new]

  if Rails.env.production?
    mount RailsAdmin::Engine => '/admin_panel', :as => 'rails_admin'
  end

  constraints ->(req) { req.env["warden"].authenticate?(scope: :user) &&
                        req.env['warden'].user.admin? } do
    mount Sidekiq::Web => '/sidekiq', :as => 'sidekiq'
  end

  get "/atom.xml" => redirect('http://blog.diasporafoundation.org/feed/atom') #too many stupid redirects :()

  get 'oembed' => 'posts#oembed', :as => 'oembed'

  # Posting and Reading
  resources :reshares

  resources :status_messages, :only => [:new, :create]

  resources :posts do
    member do
      get :next
      get :previous
      get :interactions
    end

    resources :poll_participations, :only => [:create]

    resources :likes, :only => [:create, :destroy, :index ]
    resources :participations, :only => [:create, :destroy, :index]
    resources :comments, :only => [:new, :create, :destroy, :index]
  end



  get 'p/:id' => 'posts#show', :as => 'short_post'
  get 'posts/:id/iframe' => 'posts#iframe', :as => 'iframe'

  # roll up likes into a nested resource above
  resources :comments, :only => [:create, :destroy] do
    resources :likes, :only => [:create, :destroy, :index]
  end

  # Streams
  get "participate" => "streams#activity" # legacy
  get "explore" => "streams#multi"        # legacy

  get "activity" => "streams#activity", :as => "activity_stream"
  get "stream" => "streams#multi", :as => "stream"
  get "public" => "streams#public", :as => "public_stream"
  get "followed_tags" => "streams#followed_tags", :as => "followed_tags_stream"
  get "mentions" => "streams#mentioned", :as => "mentioned_stream"
  get "liked" => "streams#liked", :as => "liked_stream"
  get "commented" => "streams#commented", :as => "commented_stream"
  get "aspects" => "streams#aspects", :as => "aspects_stream"

  resources :aspects do
    put :toggle_contact_visibility
    put :toggle_chat_privilege
  end

  get 'bookmarklet' => 'status_messages#bookmarklet'

  resources :photos, :except => [:index, :show] do
    put :make_profile_photo
  end

	#Search
	get 'search' => "search#search"

  resources :conversations do
    resources :messages, :only => [:create, :show]
    delete 'visibility' => 'conversation_visibilities#destroy'
  end

  resources :notifications, :only => [:index, :update] do
    collection do
      get :read_all
    end
  end


  resources :tags, :only => [:index]

  resources "tag_followings", :only => [:create, :destroy, :index]

  get 'tags/:name' => 'tags#show', :as => 'tag'

  resources :apps, :only => [:show]

  # Users and people

  resource :user, :only => [:edit, :update, :destroy], :shallow => true do
    get :getting_started_completed
    get :export, format: :json
    get :export_photos
  end

  controller :users do
    get 'public/:username'          => :public,           :as => 'users_public'
    get 'getting_started'           => :getting_started,  :as => 'getting_started'
    get 'privacy'                   => :privacy_settings, :as => 'privacy_settings'
    get 'getting_started_completed' => :getting_started_completed
    get 'confirm_email/:token'      => :confirm_email,    :as => 'confirm_email'
  end

  # This is a hack to overide a route created by devise.
  # I couldn't find anything in devise to skip that route, see Bug #961
  get 'users/edit' => redirect('/user/edit')

  devise_for :users, :controllers => {:registrations => "registrations",
                                      :passwords     => "passwords",
                                      :sessions      => "sessions"}

  #legacy routes to support old invite routes
  get 'users/invitation/accept' => 'invitations#edit'
  get 'invitations/email' => 'invitations#email', :as => 'invite_email'
  get 'users/invitations' => 'invitations#new', :as => 'new_user_invitation'
  post 'users/invitations' => 'invitations#create', :as => 'user_invitation'

  get 'login' => redirect('/users/sign_in')

  # Admin backend routes

  scope 'admins', :controller => :admins do
    match :user_search, via: [:get, :post]
    get   :admin_inviter
    get   :weekly_user_stats
    get   :correlations
    get   :stats, :as => 'pod_stats'
    get   "add_invites/:invite_code_id" => 'admins#add_invites', :as => 'add_invites'
  end

  namespace :admin do
    post 'users/:id/close_account' => 'users#close_account', :as => 'close_account'
  end

  resource :profile, :only => [:edit, :update]
  resources :profiles, :only => [:show]


  resources :contacts,           :except => [:update, :create] do
  end
  resources :aspect_memberships, :only  => [:destroy, :create]
  resources :share_visibilities,  :only => [:update]
  resources :blocks, :only => [:create, :destroy]

  get 'i/:id' => 'invitation_codes#show', :as => 'invite_code'

  get 'people/refresh_search' => "people#refresh_search"
  resources :people, :except => [:edit, :update] do
    resources :status_messages
    resources :photos
    get :contacts
    get "aspect_membership_button" => :aspect_membership_dropdown, :as => "aspect_membership_button"
    get :stream
    get :hovercard

    member do
      get :last_post
    end

    collection do
      post 'by_handle' => :retrieve_remote, :as => 'person_by_handle'
      get :tag_index
    end
  end
  get '/u/:username' => 'people#show', :as => 'user_profile'
  get '/u/:username/profile_photo' => 'users#user_photo'


  # Federation

  controller :publics do
    get 'webfinger'             => :webfinger
    get 'hcard/users/:guid'     => :hcard
    get '.well-known/host-meta' => :host_meta
    post 'receive/users/:guid'  => :receive
    post 'receive/public'       => :receive_public
    get 'hub'                   => :hub
  end



  # External

  resources :services, :only => [:index, :destroy]
  controller :services do
    scope "/auth", :as => "auth" do
      get ':provider/callback' => :create
      get :failure
    end
  end

  scope 'api/v0', :controller => :apis do
    get :me
  end

  namespace :api do
    namespace :v0 do
      get "/users/:username" => 'users#show', :as => 'user'
      get "/tags/:name" => 'tags#show', :as => 'tag'
    end
    namespace :v1 do
      resources :tokens, :only => [:create, :destroy]
    end
  end

  get 'community_spotlight' => "contacts#spotlight", :as => 'community_spotlight'
  # Mobile site

  get 'mobile/toggle', :to => 'home#toggle_mobile', :as => 'toggle_mobile'

  # Help
  get 'help' => 'help#faq', :as => 'help'

  #Protocol Url
  get 'protocol' => redirect("http://wiki.diasporafoundation.org/Federation_Protocol_Overview")

  #Statistics
  get :statistics, controller: :statistics

  # Terms
  if AppConfig.settings.terms.enable?
    get 'terms' => 'terms#index'
  end

  # Startpage
  root :to => 'external_data#homepage'
end

app/models/contact.rb
#   Copyright (c) 2010-2011, Diaspora Inc.  This file is
#   licensed under the Affero General Public License version 3 or later.  See
#   the COPYRIGHT file.

class Contact < ActiveRecord::Base
  belongs_to :user

  belongs_to :person
  validates :person, :presence => true

  delegate :name, :diaspora_handle, :guid, :first_name,
           to: :person, prefix: true

  has_many :aspect_memberships, :dependent => :destroy
  has_many :aspects, :through => :aspect_memberships

  has_many :share_visibilities, :source => :shareable, :source_type => 'Post'
  has_many :posts, :through => :share_visibilities, :source => :shareable, :source_type => 'Post'

  validate :not_contact_for_self,
           :not_blocked_user,
           :not_contact_with_closed_account

  validates_presence_of :user
  validates_uniqueness_of :person_id, :scope => :user_id

  before_destroy :destroy_notifications

  scope :all_contacts_of_person, ->(x) { where(:person_id => x.id) }

    # contact.sharing is true when contact.person is sharing with contact.user
  scope :sharing, -> { where(:sharing => true) }

  # contact.receiving is true when contact.user is sharing with contact.person
  scope :receiving, -> { where(:receiving => true) }

  scope :for_a_stream, -> {
    includes(:aspects, :person => :profile).
        order('profiles.last_name ASC')
  }

  scope :only_sharing, -> { sharing.where(:receiving => false) }

  def destroy_notifications
    Notification.where(:target_type => "Person",
                       :target_id => person_id,
                       :recipient_id => user_id,
                       :type => "Notifications::StartedSharing").destroy_all
  end

  def dispatch_request
    request = self.generate_request
    Postzord::Dispatcher.build(self.user, request).post
    request
  end

  def generate_request
    Request.diaspora_initialize(:from => self.user.person,
                :to => self.person,
                :into => aspects.first)
  end

  def receive_shareable(shareable)
    ShareVisibility.create!(:shareable_id => shareable.id, :shareable_type => shareable.class.base_class.to_s, :contact_id => self.id)
  end

  def contacts
    people = Person.arel_table
    incoming_aspects = Aspect.where(
      :user_id => self.person.owner_id,
      :contacts_visible => true).joins(:contacts).where(
        :contacts => {:person_id => self.user.person_id}).select('aspects.id')
    incoming_aspect_ids = incoming_aspects.map{|a| a.id}
    similar_contacts = Person.joins(:contacts => :aspect_memberships).where(
      :aspect_memberships => {:aspect_id => incoming_aspect_ids}).where(people[:id].not_eq(self.user.person.id)).select('DISTINCT people.*')
  end

  def mutual?
    self.sharing && self.receiving
  end

  def in_aspect? aspect
    if aspect_memberships.loaded?
      aspect_memberships.detect{ |am| am.aspect_id == aspect.id }
    elsif aspects.loaded?
      aspects.detect{ |a| a.id == aspect.id }
    else
      AspectMembership.exists?(:contact_id => self.id, :aspect_id => aspect.id)
    end
  end

  def self.contact_contacts_for(user, person)
    return none unless user

    if person == user.person
      user.contact_people
    else
      contact = user.contact_for(person)
      contact.try(:contacts) || none
    end
  end

  private
  def not_contact_with_closed_account
    if person_id && person.closed_account?
      errors[:base] << 'Cannot be in contact with a closed account'
    end
  end

  def not_contact_for_self
    if person_id && person.owner == user
      errors[:base] << 'Cannot create self-contact'
    end
  end

  def not_blocked_user
    if user && user.blocks.where(:person_id => person_id).exists?
      errors[:base] << 'Cannot connect to an ignored user'
      false
    else
      true
    end
  end
end

app/controllers/tags_controller.rb
#   Copyright (c) 2010-2011, Diaspora Inc.  This file is
#   licensed under the Affero General Public License version 3 or later.  See
#   the COPYRIGHT file.

class TagsController < ApplicationController
  skip_before_action :set_grammatical_gender
  before_action :ensure_page, :only => :show

  layout ->(c) { request.format == :mobile ? "application" : "with_header_with_footer" }, :only => [:show]
  use_bootstrap_for :show

  helper_method :tag_followed?

  respond_to :html, :only => [:show]
  respond_to :json, :only => [:index, :show]

  def index
    if params[:q] && params[:q].length > 1
      params[:q].gsub!("#", "")
      params[:limit] = !params[:limit].blank? ? params[:limit].to_i : 10
      @tags = ActsAsTaggableOn::Tag.autocomplete(params[:q]).limit(params[:limit] - 1)
      prep_tags_for_javascript

      respond_to do |format|
        format.json{ render(:json => @tags.to_json, :status => 200) }
      end
    else
      respond_to do |format|
        format.json{ render :nothing => true, :status => 422 }
        format.html{ redirect_to tag_path('partytimeexcellent') }
      end
    end
  end

  def show
    redirect_to(:action => :show, :name => downcased_tag_name) && return if tag_has_capitals?

    if user_signed_in?
      gon.preloads[:tagFollowings] = tags
    end
    @stream = Stream::Tag.new(current_user, params[:name], :max_time => max_time, :page => params[:page])
    respond_with do |format|
      format.json { render :json => @stream.stream_posts.map { |p| LastThreeCommentsDecorator.new(PostPresenter.new(p, current_user)) }}
    end
  end

  private

  def tag_followed?
    TagFollowing.user_is_following?(current_user, params[:name])
  end

  def tag_has_capitals?
    mb_tag = params[:name].mb_chars
    mb_tag.downcase != mb_tag
  end

  def downcased_tag_name
    params[:name].mb_chars.downcase.to_s
  end

  def prep_tags_for_javascript
    @tags = @tags.map {|tag|
      { :name  => ("#" + tag.name) }
    }

    @tags << { :name  => ('#' + params[:q]) }
    @tags.uniq!
  end
  def tosalamander
    
  end
end

app/helpers/tags_helper.rb
module TagsHelper
  def looking_for_tag_link
    return if search_query.include?('@') || normalized_tag_name.blank?
    content_tag('small') do
      t('people.index.looking_for', :tag_link => tag_link).html_safe
    end
  end

  def normalized_tag_name
    ActsAsTaggableOn::Tag.normalize(search_query)
  end

  def tag_link
    tag = normalized_tag_name
    link_to("##{tag}", tag_path(:name => tag))
  end
end

app/views/tags/_followed_tags_listings.haml
-#   Copyright (c) 2010-2011, Diaspora Inc.  This file is
-#   licensed under the Affero General Public License version 3 or later.  See
-#   the COPYRIGHT file.

= link_to t('streams.followed_tag.title'), followed_tags_stream_path, :class => 'hoverable', :data => {:stream => 'followed_tags'}
%ul#tags_list  

app/views/tags/_salamander.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<title>Pioneer Valley Citizen Science Collaboratory - Leaf Drop</title>
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<meta name="apple-mobile-web-app-capable" content="yes" />

	<link href="../bower_components/bootstrap/dist/css/bootstrap.min.css" rel="stylesheet">
	<link href="../bower_components/bootstrap/dist/css/bootstrap-theme.min.css" rel="stylesheet">

	<link href='http://fonts.googleapis.com/css?family=Open+Sans:300italic,400,300' rel='stylesheet' type='text/css'>

	<!-- <link href="../css/styles.css" rel="stylesheet"> -->

	<link rel="shortcut icon" href="/images/favicon.ico" type="image/x-icon">
	<link rel="icon" href="/images/favicon.ico" type="image/x-icon">

	<script type="text/javascript" src="../bower_components/jquery/dist/jquery.min.js"></script>
	<script type="text/javascript" src="../bower_components/bootstrap/dist/js/bootstrap.min.js"></script>

	<script type="text/javascript" src="js/app.js"></script>
</head>

<body class="projects" id="salamander-watch">

	<!-- <header class="container-fluid"></header> -->
	<div class="container-fluid">
		<h2>Salamander Watch</h2>
		<div class="row">
			<section class="col-xs-12 col-sm-8">
				<h3>Project Overview</h3>
				<p>Salamander Watch is a collaboration between Hampshire College and The Hitchcock Center for the Environment in Amherst, MA. This project involves both the “Big Night” (counting of spotted salamanders during the early spring mating migration) and the Egg Mass Count (which happens 3-4 weeks after the Big Night, and is used to get a better estimate of the breeding success and overall health of the population).</p>
				<h3 class="subsequent-heading">Spotted Salamander Basics</h3>
				<p>Adult spotted salamanders are 15-25 cm in total length, and females tend to be larger than males. Compared to other salamanders, the body is stout with a broadly rounded snout. The sides of the head are often swollen at the back of the jaw. The legs are large and strong with four to five toes. (Petranka, 1998) When they leave their ponds, spotted salamanders are black, dark brown, or dark grey on their backs...</p>
				<!-- <a class="btn btn-primary" href="http://en.wikipedia.org/wiki/Spotted_salamander" target="_blank">Read More</a> -->
			</section>
			<aside class="col-xs-12 col-sm-4">
				<h3>Salamander Watch Expeditions</h3>
				<!-- <p>Odd Future Godard fashion axe scenester. 90's, art party Austin sartorial, letterpress artisan Blue Bottle paleo Thundercats YOLO flannel vegan church-key direct trade chillwave. Literally cornhole pork belly, synth Thundercats fingerstache try-hard VHS McSweeney's. XOXO wolf literally slow-carb church-key deep.</p> -->
				<!-- <a class="btn btn-primary" href="">No Current Expeditions</a> -->
				<div class="row">
					<div class="col-xs-12 col-sm-6">
						<a class="thumbnail" href="#">
							<img alt="Launch an investigation" class="img-responsive" src="/images/launch_investigation.png"/>
						</a>
					</div>
					<div class="col-xs-12 col-sm-6">
						<a class="thumbnail" href="#">
							<img alt="Launch an investigation" class="img-responsive" src="/images/explore_data.png"/>
						</a>
					</div>
				</div>
			</aside>
		</div>
	</div>

	<!-- environmental issues -->
	<section class="container-fluid" id="environment">
		<h3>Environmental Issues Affecting Salamanders</h3>
		<div class="row issues">
			<div class="col-xs-8 col-sm-2 col-sm-offset-2">
				<a class="thumbnail" data-target="#biodiversity-icon" data-toggle="modal" href="#">
					<img alt="Biodiversity Icon" class="img-responsive" src="/images/issue_biodiversity.png"/>
					<h3 class="caption text-center">Biodiversity</h3>
				</a>
			</div>
			<div class="col-xs-8 col-sm-2">
				<a class="thumbnail" data-target="#climate-change-icon" data-toggle="modal" href="#">
					<img alt="Climate Change Icon" class="img-responsive" src="/images/issue_climatechange.png"/>
					<h3 class="caption text-center">Climate Change</h3>
				</a>
			</div>
			<div class="col-xs-8 col-sm-2">
				<a class="thumbnail" data-target="#invasive-species-icon" data-toggle="modal" href="#">
					<img alt="Invasive Species Icon" class="img-responsive" src="/images/issue_invasivespecies.png"/>
					<h3 class="caption text-center">Invasive Species</h3>
				</a>
			</div>
			<div class="col-xs-8 col-sm-2">
				<a class="thumbnail" data-target="#habitat-loss-icon" data-toggle="modal" href="#">
					<img alt="Habitat Loss Icon" class="img-responsive" src="/images/issue_habitatloss.png"/>
					<h3 class="caption text-center">Habitat Loss</h3>
				</a>
			</div>
		</div>

		<!-- Modals -->
		<!-- Biodiversity -->
		<div aria-hidden="true" aria-labelledby="biodiversity-icon" class="modal fade" id="biodiversity-icon" role="dialog" tabindex="-1">
			<div class="modal-dialog">
				<div class="modal-content">
					<!-- <div class="modal-header"> -->
						<button aria-hidden="true" class="close" data-dismiss="modal" type="button">&times;</button>
						<h4 class="modal-title" id="biodiversity-title">Biodiversity</h4>
					</div>
					<div class="modal-body row">
						<div class="col-xs-12 col-sm-4">
							<div class="thumbnail">
								<img alt="Biodiversity Icon" src="/images/modal_biodiversity.png"/>
							</div>
						</div>
						<div class="col-md-8">
							<p>The decline in amphibian populations has been both well-documented and well publicized. However, this attention is largely focused on frogs and toads. Little mention is given to salamanders or the threats that they face. This is unfortunate as the decline in salamander species is extremely significant. Around half of all the world’s salamander species are listed as Threatened by the International Union for Conservation of Nature (IUCN).</p>
							<p>These species are all facing a high risk of extinction.</p>
							<p>A further 62 species have been designated as Near-Threatened with populations that are dwindling. This means they are quickly getting closer to Threatened Status and to the brink of extinction.</p>
							<p>Sadly for some salamanders it is already too late, as both the Yunnan Lake Newt (Cynops wolterstorffi) and Ainsworth's Salamander (Plethodon ainsworthi) have already gone extinct; completely exterminated by the callous hands of humans.</p>
							<p>Salamanders have been on the earth for over 160 million years, and the terrible state that they now find themselves in is due to the detrimental acts of humans.  Even those species that are not experiencing population declines deserve attention and conservation to ensure that they remain healthy and stable.</p>
						</div>
					</div>
				</div>
			</div>
		</div>
		<!-- Climate Change -->
		<div aria-hidden="true" aria-labelledby="climate-change-icon" class="modal fade" id="climate-change-icon" role="dialog" tabindex="-1">
			<div class="modal-dialog">
				<div class="modal-content">
					<!-- <div class="modal-header"> -->
						<button aria-hidden="true" class="close" data-dismiss="modal" type="button">&times;</button>
						<h4 class="modal-title" id="climate-change-title">Climate Change</h4>
					</div>
					<div class="modal-body row">
						<div class="col-xs-12 col-sm-4">
							<div class="thumbnail">
								<img alt="Climate Change Icon" src="/images/modal_climate.png"/>
							</div>
						</div>
						<div class="col-md-8">
							<p>Climate change is among the most serious threats that salamander populations face. Detrimental changes in climate such as increased temperatures, changing humidity levels, desertification, and droughts wreak havoc on salamanders. These animals are generally adapted to moist and cool climates and may require very specific conditions to thrive. Salamanders also live a "double-life" being associated with both aquatic and terrestrial habitats.</p>
							<p>Alterations to these optimal conditions result in salamander species dwindling. Changes in climate can also effect the forming and availability of critical habitat features such as change. They state that salamanders need cool moist places to survive. The world is getting hotter and drier; temperatures in Appalachia are predicted to rise by 3 to 11 degrees Fahrenheit over the next century. Salamanders have relatively long lifespans, but they do not mature or reproduce as quickly as some other aquatic animals. They may not be able to adapt to such radical change.</p>
							<p>Biologists from the University of California, Berkeley, have reported that salamander populations in parts of Central America have declined sharply in the past 40 years and global warming could be the cause.</p>
						</div>
					</div>
				</div>
			</div>
		</div>
		<!-- Invasive Species -->
		<div aria-hidden="true" aria-labelledby="invasive-species-icon" class="modal fade" id="invasive-species-icon" role="dialog" tabindex="-1">
			<div class="modal-dialog">
				<div class="modal-content">
					<!-- <div class="modal-header"> -->
						<button aria-hidden="true" class="close" data-dismiss="modal" type="button">&times;</button>
						<h4 class="modal-title" id="invasive-title">Invasive Species</h4>
					</div>
					<div class="modal-body row">
						<div class="col-xs-12 col-sm-4">
							<div class="thumbnail">
								<img alt="Invasive Species Icon" src="/images/modal_invasive.png"/>
							</div>
						</div>
						<div class="col-md-8">
							<p>In contrast to the positive effect that round gobies have had on Lake Erie watersnakes, invasive species more typically have negative effects on native species. This is certainly true for European buckthorn, an invasive woody shrub that now occurs across a large portion of eastern North America and has displaced native plants, changed soil characteristics and patterns of nutrient cycling, and may be triggering declines of a variety of invertebrate and vertebrate species. European buckthorn is especially successful at invading flatwoods forest habitats.</p>
							<p>Such forests are underlain by a clay pan that resists water percolation, and are characterized by hydric soils and ephemeral ponds that are important amphibian breeding sites. The rarity of flatwoods forests has resulted in their recognition as globally imperiled and has made them the target of management and restoration efforts.</p>
							<p>One such effort is that of the Lake County Forest Preserve District in northeastern Illinois to restore the MacArthur Woods flatwoods forest through European buckthorn removal and drainage tile disablement. Following these restoration efforts, the District approached Dr. Carl von Ende and me with an offer to fund a PhD dissertation project aimed at assessing the feasibility of reintroducing three species of amphibians that had been extirpated from the site, spotted salamanders, woodfrogs, and spring peepers. A national search resulted in our hiring Allison Sacerdote to undertake this project. Allison conducted a series of in situ photo of Leaf Litter Methodenclosure experiments that demonstrated similar hatching success and survival to metamorphosis between restored ponds and source ponds in a neighboring county, suggesting that reintroduction should be possible.</p>
						</div>
					</div>
				</div>
			</div>
		</div>
		<!-- Habitat Loss -->
		<div aria-hidden="true" aria-labelledby="habitat-loss-icon" class="modal fade" id="habitat-loss-icon" role="dialog" tabindex="-1">
			<div class="modal-dialog">
				<div class="modal-content">
					<!-- <div class="modal-header"> -->
						<button aria-hidden="true" class="close" data-dismiss="modal" type="button">&times;</button>
						<h4 class="modal-title" id="habitat-loss-title">Habitat Loss</h4>
					</div>
					<div class="modal-body row">
						<div class="col-xs-12 col-sm-4">
							<div class="thumbnail">
								<img alt="Habitat Loss Icon" src="/images/modal_habitat.png"/>
							</div>
						</div>
						<div class="col-xs-12 col-sm-8">
							<p>One of the biggest issues affecting salamanders is the loss of their natural habitat. Many areas that were once suitable for salamanders to live have now been destroyed for developmental construction and agriculture. Habitats of all kinds are being lost at an alarming rate. Wetlands are drained, forests are logged and cut down, and waterfronts are developed. Salamanders are literally losing their homes and they are losing them rapidly! Deforestation is particularly harmful to salamanders. When the amount of shade that covers the forest floor is reduced due to the removal of trees, the increased sunlight can allow for higher temperatures to reach the forest floor.</p>
							<p>This increases the threat of desiccation. The exposed sunlight can also rapidly dry up vernal pools and temporary flooded areas on the forest floor which are crucial breeding/birthing sites. The expansion of urban areas threatens the suitable habitats that still remain.</p>
							<p>Where natural habitats do still exist, they are often fragmented or degraded. Fragmentation occurs when healthy areas of habitat are isolated from one another. These fragmented areas are known as habitat islands. Salamander populations are affected since gene flow between the populations is prevented. This increases the occurrence of inbreeding, which results in a decrease in genetic variability. Fragmented populations where inbreeding occurs often ends in a genetic bottleneck this is an evolutionary event where a significant percentage of the populartion or species is killed otherwise prevented from reproducing.</p>
						</div>
					</div>
				</div>
			</div>
		</div>
		<a class="btn btn-primary btn-back" href="index.html#projects"><span></span>Back to Projects</a>
	</section>

</body>
</html>

app/views/tags/show.haml
- content_for :page_title do
  - if @stream.tag_name
    = @stream.display_tag_name
  - else
    = t('.whatup', :pod => @pod_url)

.container-fluid#tags_show
  .row-fluid
    .span3.offset1
      %h4
        = t('.tagged_people', :count => @stream.tagged_people_count, :tag => @stream.display_tag_name)

      .side_stream.stream
        = render :partial => 'people/index', :locals => {:people => @stream.tagged_people}
        
    .span7
      .stream_container
        #author_info
          %h2
            = @stream.display_tag_name

        - if current_user
          = render 'publisher/publisher', :selected_aspects => @stream.aspect_ids, :aspect_ids => @stream.aspect_ids, :aspect => @stream.aspect
          

        %hr
        #main_stream.stream

        #paginate
          %span.loader.hidden

        / %iframe{:frameborder => "0", :align => "middle", :height => "800", :src => 'tosalamander', :width => "100%"}


      %a{:id=>"back-to-top", :title=>"#{t('layouts.application.back_to_top')}", :href=>"#"}
        &#8679;
  - if @stream.tag_name == "salamander"       
    %iframe{:frameborder => "0", :align => "middle", :height => "1400", :src => 'tosalamander', :width => "100%"}
    
    / .span7
    /   .stream_container
    /     - if current_user


/ .container-fluid
/   = render 'tags/salamander'

app/views/tags/show.mobile.haml
-#   Copyright (c) 2010-2011, Diaspora Inc.  This file is
-#   licensed under the Affero General Public License version 3 or later.  See
-#   the COPYRIGHT file.

%h1
  = @stream.display_tag_name

#main_stream.stream
  = render 'shared/stream', :posts => @stream.stream_posts
  = render 'shared/stream_more_button'

app/views/tags/update.js.erb
var tagName = "<%= escape_javascript(@tag.name) %>"
$("#followed_tags_listing").find("#tag-following-"+tagName).slideUp(100);
Diaspora.page.flashMessages.render({success: true, notice: Diaspora.I18n.t("tags.wasnt_that_interesting", {tagName: tagName})});